# Generated by Django 4.1.5 on 2023-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='imgaes')),
            ],
        ),
    ]
